# CWSXM3107E Exception while setting the transformed DataObject back into the root location. This has been reported by the following entity: 0

## Explanation

## User response